# Generated by Django 5.1.7 on 2025-03-27 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veterinarias', '0002_auto_20250327_0003'),
    ]

    operations = [
    ]
