# Generated by Django 5.1.7 on 2025-03-29 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veterinarias', '0003_auto_20250327_0007'),
    ]

    operations = [
    ]
