# Generated by Django 5.1.7 on 2025-04-08 00:54

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veterinarias', '0004_auto_20250328_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='veterinaria',
            name='servicios',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('spa', 'Spa'), ('consulta', 'Consulta veterinaria'), ('cirugia', 'Cirugía'), ('farmacia', 'Farmacia'), ('accesorios', 'Venta de accesorios'), ('comida', 'Venta de comida'), ('domicilio', 'Servicio a domicilio'), ('pension', 'Pensión'), ('emergencias', 'Emergencias')], max_length=77),
        ),
    ]
